title: Overview of Computer Architecture (COMSM1302)
description: Page for the Overview of Computer Architecture unit of the University of Bristol computer science conversion MSc, code COMS20010.
theme: just-the-docs

url: https://cs-uob-overview-of-architecture.github.io
color_scheme: dark

nav_external_links:
  - title: Attendance (Qwickly)
    url: https://www.ole.bris.ac.uk/webapps/blackboard/content/listContentEditable.jsp?content_id=_8662659_1&course_id=_260193_1&mode=reset
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false